### ISSUE TITLE
Empty alert if domain doen"t resolve

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/monitoring#15]
If we monitor a domain which doesn't resolve we received alert with no change :(

**Comment by FafnerKeyZee** [comment]
```
          

    Comparison settings:

          {}
          

    Next capture: 2023-05-17T21:08:01.768801
    4 captures available.
    Last one triggered at 2023-05-17T20:07:51.738039

Comparison of the two most recent captures:

  {
  "message": "Internal Server Error"
}
  ``

**Comment by Rafiot** [comment]
Getting an internal server error is probably because something went poorly on Lookyloo side. If that happen again, can you add the error on the logs from lookyloo?

In theory, this bug is fixed by now, but I'll need more details if it isn't.

**Comment by Rafiot** [comment]
Actually, forget about it, there is in fact an issue, should be fixed later today.
