### ISSUE TITLE
Expiration date is required when updating with the form

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/monitoring#21]
HEllo,

When we use the interface, we have to set an expiration date. Can you allow to don't give any expiration date.

BR,

**Comment by FafnerKeyZee** [comment]
Should be fixed using this code:
```expire_at = DateTimeField('Expire monitoring at', validators=[validators.Optional()])```

**Comment by Rafiot** [comment]
Fixed by: https://github.com/Lookyloo/monitoring/commit/a16aad9d7762ff2f867e14322060ba4d8aef72bf
