### ISSUE TITLE
Add a delay before sending email 

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/monitoring#25]
Hello,

In some case we got error in the email when alerting:
"We have HAR files nd need to rebuild the tree"

But when checking on the website few minutes after, all the comparison is done.

Looks like we need to had more time before sending the email.

BR

**Comment by Rafiot** [comment]
This issue should be fixed by that: https://github.com/Lookyloo/lookyloo/commit/4143d5f249b6c567f0b1f96b53807d890a2e7f47
