### ISSUE TITLE
DNS Timeout for "xxxxx"

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/monitoring#28]
Hello,

I'm using the project with LACUS (latest version) and we got for some domains the error:
``` DNS Timeout for "XXXXXXXXX.com": The resolution lifetime expired after 3.202 seconds: Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out. ``` 

It's working fine for other captures via lookyloo and many urls on monitor, but few of them give me this error 2 or 3 times per day.

Regards

**Comment by Rafiot** [comment]
I've seen that too, but it's the DNS resolution by the DNS server that is taking too much time. The best I can do it trying to trigger a retry when that happens, but there is not much else I can do as the resolution isn't made from withing the project.

**Comment by FafnerKeyZee** [comment]
Yep we can try this :-)
